# Generated by Django 6.0.7 on 2026-07-17 06:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Например: дома, в спортзале, в офисе', max_length=255, verbose_name='Место выполнения')),
                ('time', models.TimeField(help_text='Укажите время суток', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Например: сделать 20 приседаний, выпить стакан воды', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Отметьте, если привычка является приятной (вознаграждением)', verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Интервал выполнения привычки в днях (по умолчанию 1 — каждый день)', verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Чем вы себя вознаградите, если нет связанной приятной привычки', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Сколько времени займет выполнение (не более 2 минут)', verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, help_text='Сделать привычку видимой для всех пользователей', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Привяжите приятную привычку к полезной', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useful_habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('id',),
            },
        ),
    ]
